using Algorithms;
CustomList<int> customList = new CustomList<int>();
customList.Add(1);
customList.Add(2);
customList.Add(3);
customList.Add(4);
customList.Add(5);
customList.Add(6);
customList.Add(7);
customList.Add(8);
customList.Add(9);
//Console.WriteLine(customList.Find(x => x % 2 == 0));
//Console.WriteLine(customList.FindAll(x => x % 2 == 0).Count);
//Console.WriteLine(customList.Contains(5));
//Console.WriteLine(customList.Remove(4));
//Console.WriteLine(customList.Exists(x => x % 2 == 0));